### ISSUE TITLE
Usage examnples? 

### ISSUE THREAD

**Issue by johntdyer** [savdagod/TidbytAssistant#1]
Looks promising, any examples of how to use it w/ Tidbyt?

**Comment by savdagod** [comment]
I actually have a package that I will upload that will make this way easier. It creates the command line service and a script so it’s easy to call and select parameters.

**Comment by motoridersd** [comment]
Did you have that script handy?

I use the command_line integration as a switch to turn services on/off on my Debian container, and to delete apps from the Tidbyt.

The shell integration has changed a bit in the past few months, so wondering how you're doing it today.

**Comment by savdagod** [comment]
Sorry for the late response. I updated the script, added tidbyt.yaml which is a package you should add to HA and updated the README to give a brief overview. Let me know if you need help.
