### ISSUE TITLE
Setting a custom timeout in the configuration is broken

### ISSUE THREAD

**Issue by IngmarStein** [savdagod/TidbytAssistant#16]
Specifying a timeout in configuration.yaml like

```
tidbytassistant:
  timeout: 60
```

results in this exception:

```
  File "/config/custom_components/tidbytassistant/__init__.py", line 90, in setup
    timeout = time.time() + conf.get(CONF_TIMEOUT,DEFAULT_TIMEOUT)
              ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

It looks like this is because it's parsed as a string: `vol.Optional(CONF_TIMEOUT): cv.string` (the default case works because it's not a string: `DEFAULT_TIMEOUT = 30`)

**Comment by savdagod** [comment]
Yeah the whole loop until timeout thing doesn’t actually work when you reboot the machine. The loop hangs up the entire boot process even when everything is async. I changed the code to just check if the add-on is installed and config option to skip the check if someone has the add-on on a different machine. I will push the updated code in a bit.

**Comment by savdagod** [comment]
Removed this in 1.0.15/6.

**Comment by IngmarStein** [comment]
1.0.15/16 broke the integration startup for me:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/addon_manager.py", line 53, in wrapper
    return_value = await func(self, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/hassio/addon_manager.py", line 152, in async_get_addon_info
    addon_store_info = await self._supervisor_client.store.addon_info(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.addon_slug
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohasupervisor/store.py", line 31, in addon_info
    result = await self._client.get(f"store/addons/{addon}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohasupervisor/client.py", line 154, in get
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohasupervisor/client.py", line 122, in _request
    raise exc_type(result.message, result.job_id)
aiohasupervisor.exceptions.SupervisorBadRequestError: Addon 557a5a82_tidbytassistant with version latest does not exist in the store
```

**Comment by IngmarStein** [comment]
Looks like `ADDON_SLUG` is different in my installation. The code expects `557a5a82_tidbytassistant`, but mine is `d8f2112a_tidbytassistant`. Given that the prefix is computed from the GitHub URL (as per https://developers.home-assistant.io/docs/add-ons/communication/#network), I wonder why it is different.

**Comment by IngmarStein** [comment]
The add-on store page shows that I installed the add-on from `https://github.com/savdagod/ha-addons`:

<img width="383" alt="image" src="https://github.com/user-attachments/assets/08ff96bd-8135-4fbe-8100-caeab44d3eb7">

Did you use some other URL which results in a different slug?

**Comment by savdagod** [comment]
I had the right url, but went ahead and deleted them readded it and now it matches what you have. I then somehow accidentally added the repo again (which shouldn’t be possible) and the second one had my original hash. I must have done that previously as well and deleted the original instead of the duplicate.

**Comment by attilhacks** [comment]
Hi, is there any way to set a timeout for the text displayed? The app rotation is overriding it

thanks

**Comment by savdagod** [comment]
> Hi, is there any way to set a timeout for the text displayed? The app rotation is overriding it
> 
> thanks

No there isn’t. The timeout here is for the amount of time the integration will attempt to connect to the add-on so that it can load correctly. Tidbyt apps have a set amount of time they display. The only “timeout” I have found is how long an app displays before it loops again but the time the app is up is a fixed amount of time.
