### ISSUE TITLE
Error setting up last version

### ISSUE THREAD

**Issue by attilhacks** [savdagod/TidbytAssistant#17]
Hello, just upgraded HA and Tidbyt integration but getting this error

No issues found for search term 'tidbytassistant'
aiohasupervisor.exceptions.SupervisorBadRequestError: Addon d8f2112a_tidbytassistant with version latest does not exist in the store
  File "/config/custom_components/tidbytassistant/__init__.py", line 125, in async_setup
homeassistant.components.hassio.addon_manager.AddonError: Failed to get the TidbytAssistant add-on info: Addon d8f2112a_tidbytassistant with version latest does not exist in the store

any hint?
thanks

**Comment by nickschiffer** [comment]
Getting the same error.

**Comment by savdagod** [comment]
It’s because you don’t have the addon/repo. The docs state you need to install the addon first.

**Comment by attilhacks** [comment]
addon is installed...

<img width="629" alt="Screenshot 2024-12-08 at 21 01 19" src="https://github.com/user-attachments/assets/b7949f48-5929-4f08-8c90-e29f8b671dcb">

**Comment by attilhacks** [comment]
Addon is installed

<img width="495" alt="Screenshot 2024-12-08 at 21 02 38" src="https://github.com/user-attachments/assets/4e50469c-2f75-42da-b2f0-6411704b0bc3">

**Comment by savdagod** [comment]
That’s not the addon. The addon is a separate thing: https://github.com/savdagod/ha-addons

Once you install this you will be able to use the integration.
