### ISSUE TITLE
Text Not Sending to Device

### ISSUE THREAD

**Issue by roomonthethird** [savdagod/TidbytAssistant#2]
Hey there!

After installing TidbytAssistant I tried to get it working with just a test automation --- when this LED turns on / off, send message.

Tried a few times, nothing happened. In the log I got the following message:

```
[webhook] 2024/09/14 01:54:51 [c95d09] command output: /opt/TidbytText.sh: line 19: pixlet: not found
/opt/TidbytText.sh: line 21: pixlet: not found

[webhook] 2024/09/14 01:54:51 [c95d09] error occurred: exit status 127
[webhook] 2024/09/14 01:54:51 [c95d09] finished handling tidbyt-text
```

Before this text it says that the webhook is successfully sent, including all my API info.

**Comment by savdagod** [comment]
What version of the add-on are you running? Also what are you running it on? Had an issue with raspberry pis not installing correctly and I had that fixed so this might be an arm64 related issue that I need to account for.

**Comment by roomonthethird** [comment]
I'm the same user from Reddit with the Raspberry Pi lol -- 

running the latest of the add-on (1.0.2) using a Raspberry Pi 4, running HA core 2024.9.1, os13.1

**Comment by savdagod** [comment]
Ah yeah haha I think I can fix this issue, give me a sec

**Comment by savdagod** [comment]
I just pushed an update to the add-on, 1.0.3. Let me know if that fixes it for you.

**Comment by roomonthethird** [comment]
Updated to 1.0.3, same error message

**Comment by savdagod** [comment]
Check for update, rebuild and try again. I updated it to use the latest Pixlet version which could give you the error. If it still throws that error, Ill find some time to test it on my Respberry Pi.

**Comment by roomonthethird** [comment]
I reinstalled--same error message

**Comment by savdagod** [comment]
does it say pixlet not found or does it now say /usr/local/bin/pixlet not found?

**Comment by roomonthethird** [comment]
```
[webhook] 2024/09/14 15:37:59 [2fc2b8] command output: /opt/TidbytText.sh: line 19: /usr/local/bin/pixlet: not found
/opt/TidbytText.sh: line 21: /usr/local/bin/pixlet: not found

[webhook] 2024/09/14 15:37:59 [2fc2b8] error occurred: exit status 127
[webhook] 2024/09/14 15:37:59 [2fc2b8] finished handling tidbyt-text
```

Tried to do a push and got this:

```
[webhook] 2024/09/14 15:59:04 [0e537d] command output: /opt/TidbytPush.sh: line 18: /usr/local/bin/pixlet: not found
/opt/TidbytPush.sh: line 20: /usr/local/bin/pixlet: not found
```

**Comment by sbryce1** [comment]
I'm having the same issue.  Raspberry Pi 4.

**Comment by savdagod** [comment]
Try out 1.0.5 of the Docker container. It now builds the picket binary instead of pulling it which might fix the issue you guys are having.

**Comment by sbryce1** [comment]
command output: Error: failed to load applet: starlark.ExecFile: cannot load render.star: circular dependency detected: render.star -> render.star
Error: failed to read file /tmp/render.webp: open /tmp/render.webp: no such file or directory

**Comment by savdagod** [comment]
Check for update and rebuild. I had to fix the scripts, should be working now.

Also this is a good sign, as the Pixlet app seems to actually be working now when before it wasn’t.

**Comment by sbryce1** [comment]
It works! Thank you so much! This is dope!

**Comment by savdagod** [comment]
Hell yeah, glad it’s working for you!

@roomonthethird  should be working for you too, so I’m going to close this issue.

**Comment by roomonthethird** [comment]
Working on my end too!! Thank you!!!
