### ISSUE TITLE
Example Star Files - Pushing Custom Content

### ISSUE THREAD

**Issue by a-bianucci** [savdagod/TidbytAssistant#5]
Hello.

Trying to work on developing a personalized Sensor from Hassio to display on the Tidbyt.

I was unable to get it to work.  As part of my troubleshooting, I tried taking some of the star files from: https://github.com/savdagod/ha-addons/blob/main/TidbytAssistant/display/ and pasting them into a file called example in the /config/tidbyt folder as the guides have provided.   Even that wouldn't display.

What potential step could I be missing, or is there an example.star file that I could put in that config/tidbyt folder to validate everything is working as expected?  Leveraging the addon in general to push text for instance does work currently.

**Comment by savdagod** [comment]
What is the error you are getting in the add-on logs? I just pushed v1.0.4 for the integration and v1.0.6 for the add-on that may fix whatever issue you are having.

**Comment by savdagod** [comment]
Closing this issue. If you’re still having trouble I can help you out further no problem. This feature is indeed working on the latest version for me and other users.
