### ISSUE TITLE
Publish App to Screen

### ISSUE THREAD

**Issue by sbryce1** [savdagod/TidbytAssistant#6]
In the most recent update, you changed app publishing to go to the background.  For my use case, I wanted the information to pop up on screen when I published.  Would it be possible to add a toggle in the Publish settings to allow for Foreground or Background publishing?

Thank you.

**Comment by savdagod** [comment]
Yessir, I can add that for you. Might be able to get it implemented by the end of the day.

**Comment by savdagod** [comment]
I added this feature. let me know if you have anything else you'd like to see added.
