### ISSUE TITLE
FR: expose Tidbyts as lights

### ISSUE THREAD

**Issue by IngmarStein** [savdagod/TidbytAssistant#9]
This could be used to set the brightness as it's already possible with the SetBrightness service call.

**Comment by savdagod** [comment]
I found it cleaner with its own service call which can set the auto dim setting but I think a light would make sense as well so that it can capture the current state. I can also make auto dim a separate switch.

**Comment by IngmarStein** [comment]
Light + auto-dim switch sounds like a good idea. As you said, the main motivation for this is to expose the current state.

**Comment by savdagod** [comment]
Added to v1.0.9
